#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: tetris
    tanzu.app.live.view: "true"
  name: tetris
  namespace: #@ data.values.namespace
spec:
  build:
    env:
      - name: BP_DOTNET_PROJECT_PATH
        value: "./SampleApp"
      - name: BP_DOTNET_PUBLISH_FLAGS
        value: "--verbosity=normal --self-contained=true"
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: dotnet-core
      apps.tanzu.vmware.com/build-engine: dotnet-3.1
  source:
    git:
      url: https://github.com/aboudoux/TetrisBlazor
      ref:
        branch: master
