#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: pacman
    tanzu.app.live.view: "true"
  name: pacman
  namespace: #@ data.values.namespace
spec:
  build:
    env:
      - name: BP_DOTNET_PROJECT_PATH
        value: "./src/PacMan"
      - name: BP_DOTNET_PUBLISH_FLAGS
        value: "--verbosity=normal --self-contained=true"
  source:
    git:
      url: https://github.com/pacphi/PacManBlazor
      ref:
        branch: master
