#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: weather-app
  name: weather-app
  namespace: #@ data.values.namespace
spec:
  source:
    git:
      url: https://github.com/ComputerScientist-01/Weather-app-heroku.git
      ref:
        branch: master
